abbr -a -U -- df 'df -Th --total'
abbr -a -U -- du 'du -h'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gg 'gitg &'
abbr -a -U -- gka 'gitk --all'
abbr -a -U -- gl 'git log --oneline --graph --decorate --all'
abbr -a -U -- gs 'git status'
abbr -a -U -- gss 'git status -s'
abbr -a -U -- lessn 'less -N'
abbr -a -U -- pbcopy 'xclip -selection clipboard'
abbr -a -U -- pbpaste 'xclip -selecton clipboard -o'
abbr -a -U -- psg 'ps aux | grep -v grep | grep -i -e VSZ -e'
